#!/bin/bash

echo "BigBootyHunter Mobile Miner Installtion Script 0.1"
apt-get update && apt-get upgrade
apt-get install wget
apt-get install proot
apt-get install git
cd
git clone git://github.com/MFDGaming/ubuntu-in-termux.git
ls
cd ubuntu-in-termux
ls
chmod +x ubuntu.sh
./ubuntu.sh
./starubuntu.sh
apt update
apt upgrade
apt-get install git build-essential cmake libuv1-dev libmicrohttpd-dev libssl-dev
git clone git://github.com/xmrig.git
cd xmrig
ls
mkdir build
ls
cd build
apt-get update
apt-get install libhwloc-dev
cmake..
make
exit
exit

