#!/bin/bash
#.   curl -o booty.sh https://raw.githubusercontent.com/hexnano/booty/main/miner
#.   chmod +x booty.sh
#    ./booty.sh


echo "####### BigBootyHunter's Mobile Miner Installation Script V2 ########"
base64 -d <<<"H4sIAJM2MVYAA1NQgAEDIIhHBsgCBmgAU8TAQJsL2SgU41AFiDALYRhUF8I0NAEUCbBZUB7MBGRrUXX
g8DC6CagORwkYtDCDcw3IMwDdOBL1IyRRwpBI7cihTlSYkRRNUHcRnUZgXIQGIlOoOQC/4ufk0gIAAA==" | gunzip
apt-get update  
apt-get upgrade
echo "yes" | apt-get install wget
apt-get install proot
apt-get install git
cd
git clone git://github.com/MFDGaming/ubuntu-in-termux.git
ls
cd ubuntu-in-termux
ls
chmod +x ubuntu.sh
./ubuntu.sh
./startubuntu.sh
apt update
apt upgrade
apt-get install git build-essential cmake libuv1-dev libmicrohttpd-dev libssl-dev
git clone git://github.com/xmrig/xmrig.git
cd xmrig
ls
mkdir build
ls
cd build
apt-get update
apt-get install libhwloc-dev
cmake ..
make
exit
exit

